[build]
  base = "New QUiz"
  command = "npm install && npm run build"
  publish = "client/dist"

[functions]
  directory = "server/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 